config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views


app_name = "reviews"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<str:performance_pk>/<int:review_pk>/update/", views.update, name="update"),
    path("<str:performance_pk>/<int:review_pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/comment_create/", views.comment_create, name="comment_create"),
    path("comment_delete/<int:pk>/", views.comment_delete, name="comment_delete"),
]

reviews/models.py
from django.db import models
from django.conf import settings
from articles.models import PlayDetail


class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    grades = [
        ("1", "⭐"),
        ("2", "⭐⭐"),
        ("3", "⭐⭐⭐"),
        ("4", "⭐⭐⭐⭐"),
        ("5", "⭐⭐⭐⭐⭐"),
    ]
    grade = models.CharField(max_length=20, choices=grades, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    playId = models.ForeignKey(PlayDetail, on_delete=models.CASCADE)


class ReviewPhoto(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", blank=True)


class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

reviews/forms.py
from django import forms
from .models import ReviewPhoto, Review, Comment
from django.forms import ClearableFileInput, Textarea, TextInput


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "content",
            "grade",
        ]
        labels = {
            "content": "관람후기",
            "grade": "별점",
        }
        widgets = {
            "content": Textarea(
                attrs={
                    "placeholder": "후기를 작성해주세요.",
                }
            )
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        labels = {
            "content": "",
        }
        widgets = {
            "content": TextInput(
                attrs={
                    "placeholder": "댓글 달기",
                }
            )
        }


class ReviewPhotoForm(forms.ModelForm):
    class Meta:
        model = ReviewPhoto
        fields = ("image",)
        widgets = {
            "image": ClearableFileInput(
                attrs={
                    "multiple": True,
                    "id": "image_field",
                    "style": "height: 100px; width: 100px; border: 1px dashed #adb5bd; color: #adb5bd;",
                }
            ),
        }
        labels = {
            "image": "다중 클릭하여 사진을 여러장 올릴 수 있어요!",
        }

reviews/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReviewForm, ReviewPhotoForm, CommentForm
from articles.models import PlayDetail
from .models import ReviewPhoto, Review, Comment
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import JsonResponse


def index(request):

    reviews = Review.objects.all()

    context = {
        "reviews": reviews,
    }

    return render(request, "reviews/index.html", context)


@login_required
def create(request):
    # 임시로 넣음
    play = PlayDetail.objects.get(pk=1)
    if request.method == "POST":
        review_form = ReviewForm(request.POST)
        reviewPhoto_form = ReviewPhotoForm(request.POST, request.FILES)
        # 추후 pk 부분 수정해야 함
        playId = PlayDetail.objects.get(pk=1)

        images = request.FILES.getlist("image")
        if review_form.is_valid() and reviewPhoto_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.playId = playId
            if len(images):
                for image in images:
                    image_instance = ReviewPhoto(review=review, image=image)
                    review.save()
                    image_instance.save()
            else:
                review.save()
            # return redirect("articles:concert")
            return redirect("reviews:index")
    else:
        review_form = ReviewForm()
        reviewPhoto_form = ReviewPhotoForm()
    context = {
        "review_form": review_form,
        "reviewPhoto_form": reviewPhoto_form,
        "play": play,
    }

    return render(request, "reviews/create.html", context)


def detail(request, pk):

    review = Review.objects.get(pk=pk)
    comments = Comment.objects.filter(review=review).order_by("-pk")
    comment_form = CommentForm()

    context = {
        "review": review,
        "comment_form": comment_form,
        "comments": comments,
    }

    return render(request, "reviews/detail.html", context)


@login_required
def update(request, performance_pk, review_pk):
    play = PlayDetail.objects.get(playid=performance_pk)
    review = Review.objects.get(pk=review_pk)
    photos = ReviewPhoto.objects.filter(review=review)

    print(request.POST.get("grade"))
    print(review)

    if request.method == "POST":
        review_form = ReviewForm(request.POST, instance=review)
        reviewPhoto_form = ReviewPhotoForm(request.POST, request.FILES)
        images = request.FILES.getlist("image")
        for photo in photos:
            if photo.image:
                photo.delete()
        if review_form.is_valid():
            review = review_form.save(commit=False)
            if len(images):
                for image in images:
                    image_instance = ReviewPhoto(review=review, image=image)
                    review.save()
                    image_instance.save()
            else:
                review.save()
            review.save()
            return redirect("articles:detail", performance_pk)
    else:
        review_form = ReviewForm(instance=review)
    if photos:
        reviewPhoto_form = ReviewPhotoForm(instance=photos[0])
    else:
        reviewPhoto_form = ReviewPhotoForm()

    context = {
        "review_form": review_form,
        "reviewPhoto_form": reviewPhoto_form,
        "play": play,
    }

    return render(request, "reviews/create.html", context)


@login_required
def delete(request, performance_pk, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    performance = get_object_or_404(PlayDetail, playid=performance_pk)
    if request.user == review.user:
        review = Review.objects.get(pk=review_pk)
        review.delete()
        return redirect("articles:detail", performance_pk)
    else:
        return render(
            request,
            "articles/detail.html",
            {
                "performance": performance,
                "review": review,
            },
            performance_pk,
        )


def comment_create(request, pk):
    print(request.POST)
    review = Review.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    print("실행되나?")
    user = request.user.pk
    temp = Comment.objects.filter(review_id=pk).order_by("-pk")
    comment_data = []

    for tem in temp:
        comment_data.append(
            {
                "user_pk": tem.user_id,
                "userName": tem.user.username,
                "content": tem.content,
                "commentPk": tem.pk,
                "commentDate": tem.created_at.strftime("%y-%m-%d"),
            }
        )
    context = {
        "comment_data": comment_data,
        "review_pk": review.pk,
        "user": user,
    }
    print(context)
    return JsonResponse(context)


def comment_delete(request, pk):
    print(request.POST)
    comment = Comment.objects.get(pk=pk)
    review = comment.review
    comment.delete()

    user = request.user.pk
    temp = Comment.objects.filter(review=review).order_by("-pk")
    comment_data = []

    for tem in temp:
        comment_data.append(
            {
                "user_pk": tem.user_id,
                "userName": tem.user.username,
                "content": tem.content,
                "commentPk": tem.pk,
                "commentDate": tem.created_at.strftime("%y-%m-%d"),
            }
        )
    context = {
        "comment_data": comment_data,
        "review_pk": review.pk,
        "user": user,
    }
    print("실행")
    return JsonResponse(context)

reviews/templates/reviews/create.html
{% comment %} {% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
{% include 'nav.html' %}

<div class="container mt-5">
  <!-- Button trigger modal -->
  <button type="button" class="rc-btn mt-5" data-bs-toggle="modal" data-bs-target="#review_updateModal">
    관람 후기 등록
    <i class="fa-solid fa-pen"></i>
  </button>

  <!-- Modal -->
  <div class="modal fade" id="review_updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{ play.playname }}</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- Review-Form -->
          <form id="review-create" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form review_form %}
            {% bootstrap_form reviewPhoto_form %}
          </form>
        </div>
        <div class="modal-footer justify-content-center">
          <button type="submit" class="rc-btn" data-bs-dismiss="modal">취소</button>
          <button type="submit" class="rc-btn" onclick="document.forms['review-create'].submit();">등록</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Review update -->
  <!-- Button trigger modal -->
  <a data-bs-toggle="modal" href="#update-form" style="border: 0; background: none;">
    리뷰수정
  </a>

  <!-- Review update Modal -->
  <div class="modal fade" id="update-form" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">
            관람 후기 수정
            <span class="ms-2" style="color: var(--gray-dark-color); font-size: 16px;">
              {{ performance.playname }}
            </span>
          </h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- Review update Form -->
          <form id="review-update" action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% bootstrap_form review_form %}
          {% bootstrap_form reviewPhoto_form %}
          </form>
        </div>
        <div class="modal-footer justify-content-center">
          <button type="submit" class="rc-btn" data-bs-dismiss="modal">취소</button>
          <button type="submit" class="rc-btn" onclick="document.forms['review-update'].submit();">수정</button>
        </div>
      </div>
    </div>
  </div>


  
  <!-- 폼 비교중 -->
  <hr>
  <!-- Review update Form -->
  <form id="review-update" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form review_form %}
    {% bootstrap_form reviewPhoto_form %}
  </form>
  <hr>

  <!-- Form Custom -->
  <form action="" id="update-custom">
    <!-- textarea -->
    <label for="textarea">관람후기</label>
    <textarea name="" id="textarea" class="form-control" cols="30" rows="10" placeholder="후기를 작성해주세요."></textarea>
    <!-- select -->
    <label for="select">별점</label>
    <select name="order" form="update-custom" id="select" class="form-select">
      <option value="">---------</option>
      <option value="">⭐️</option>
      <option value="">⭐️⭐️</option>
      <option value="">⭐️⭐️⭐️</option>
      <option value="">⭐️⭐️⭐️⭐️</option>
      <option value="">⭐️⭐️⭐️⭐️⭐️</option>
    </select>
    <!-- image file -->
    <label for="images">다중 클릭하여 사진을 여러장 올릴 수 있어요!</label>
    <input class="form-control" type="file" src="#" alt="제출버튼" multiple id="images">
  </form>


</div>

{% include 'sub-footer.html' %}
{% endblock content %} {% endcomment %}

reviews/templates/reviews/detail.html
{% comment %} {% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
{% include 'main-nav.html' %}

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  버튼
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <!-- Modal Content -->
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <h1 class="modal-title fs-5 me-3">
          관람 후기 
          <span class="ms-2" style="color: var(--gray-dark-color); font-size: 16px;">
            {{ review.playId.playname }}
          </span>
        </h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <!-- Modal Body -->
      <div class="modal-body" style="height: 700px; overflow-y: scroll">
        <!-- User Info -->
        <div class="fs-5 d-flex align-items-center justify-content-end" id="exampleModalLabel">
          <!-- Btn: Update & Delete -->
          {% if review.user == request.user %}
          <div class="d-flex align-items-center me-2" style="font-size: 14px;">
            <a href="{% url 'reviews:update' review.pk %}" class="me-1">
              <i class="fa-solid fa-pen"></i>
            </a>
            <form action="{% url 'reviews:delete' review.pk %}" method="POST">
              {% csrf_token %}
              <button type="submit" style="border: 0; background: none;">
                <i class="fa-solid fa-trash-can"></i>
              </button>
            </form>
          </div>
          {% endif %}
          <div class="d-flex pe-3" style="color: var(--main-color); font-size: 14px;">
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
          </div>
          <div class="px-3" style="border-left: 1px solid var(--gray-light-color); border-right: 1px solid var(--gray-light-color); font-size: 14px;">
            {{ review.user.username }}
          </div>
          <div class="ps-3" style="font-size: 14px;">
            {{ review.created_at|date:"Y-m-d" }}
          </div>
        </div>
        <!-- Review-Photo -->
        <div class="my-3 d-flex flex-column align-items-center">
          {% for photo in review.reviewphoto_set.all %}
          <div class="mb-2" style="width: 10rem; height: 10rem;">
            <img src="{{ photo.image.url }}" alt="" style="height: 10rem; width:10rem;">
          </div>
          {% endfor %}
        </div>
        <p>{{ review.content }}</p>
        <hr>

        <!-- Comment Create Form -->
        {% if request.user.is_authenticated %}
        <form id="comment-form" data-review-id="{{ review.pk }}">
          {% csrf_token %}
          {% bootstrap_form comment_form %}
          <input type="submit" value="댓글생성" style="display: none;">
        </form>
        {% endif %}


        <!-- Comment List -->
        <div id="comments">
          <p class="fw-bold">댓글 목록</p>          
          <hr>
          {% if review.comment_set.first %}
            {% for comment in comments %}
            <div class="d-flex justify-content-between mb-1">
              <div class="">
                <p class="mb-2" style="font-weight: 500;">{{ comment.user }}</p>
                <p>{{ comment.content }}</p>
              </div>
              <span>
                {% if request.user == comment.user %}
                  {{ comment.created_at|date:"Y-m-d" }}
                  <button class="float-end comment-del" onclick="comment_delete(this)" id="comment-delete-{{ comment.pk }}" data-commentdel-id="{{ comment.pk }}" style="border: 0; background: none;">
                    삭제
                  </button>
                {% endif %}
              </span>
            </div>
            <hr>
            {% endfor %}
          {% else %}
          <div class="d-flex justify-content-center my-5" style="color: var(--gray-color);">
            댓글이 없어요...
          </div>
          {% endif %}
            
        </div>
      </div>
    </div>
    <!-- Modal Content-End -->
  </div>
</div>

{% include 'sub-footer.html' %}
{% endblock content %}


<!-- JS -->
{% block js %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<!-- Comment Create -->
<script>
  const commentForm = document.querySelector('#comment-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value
  
  commentForm.addEventListener('submit', function(event){
    event.preventDefault()
    axios({
      method: 'post',
      url: `/reviews/${event.target.dataset.reviewId}/comment_create/`,
      headers: {'X-CSRFToken': csrftoken},
      data: new FormData(commentForm)
    })
    .then(response => {
      console.log(response.data)
      commentForm.reset()
      const comments = document.querySelector('#comments')
      comments.textContent = ""
      const comment_data = response.data.comment_data
      const user = response.data.user

      for (let i = 0; i < comment_data.length; i++){
        const review_pk = response.data.review_pk
        if (user === comment_data[i].user_pk){
          comments.insertAdjacentHTML('beforeend',  
          `
          <div class="d-flex justify-content-between mb-1">
            <div class="">
              <p class="mb-2" style="font-weight: 500;">${ comment_data[i].userName }</p>
              <p>${ comment_data[i].content }</p>
            </div>
            <span>
              ${ comment_data[i].commentDate }
              <button class="float-end comment-del" onclick="comment_delete(this)" id="comment-delete-${comment_data[i].commentPk}" data-commentdel-id="${comment_data[i].commentPk}" style="border: 0; background: none;">
                삭제
              </button>
            </span>
          </div>
          <hr>
          `)
        } else {
          comments.insertAdjacentHTML('beforeend',  
          `
          <p>${ comment_data[i].userName }: ${ comment_data[i].content }</p>
          `)
        }
      }
    })
  })
</script>

<!-- Comment Delete -->
<script>
  
  const comment_delete = (e) => {
    axios({
      method: 'post',
      headers: {'X-CSRFToken': csrftoken},
      url: `/reviews/comment_delete/${event.target.dataset.commentdelId}/`,
    })
    .then(response => {
      console.log(response.data)
      const comments = document.querySelector('#comments')
      comments.textContent = ""
      const comment_data = response.data.comment_data
      const user = response.data.user
      for (let i = 0; i < comment_data.length; i++){
        const review_pk = response.data.review_pk
        if (user === comment_data[i].user_pk){
          comments.insertAdjacentHTML('beforeend',  
          `
          <div class="d-flex justify-content-between mb-1">
            <div class="">
              <p class="mb-2" style="font-weight: 500;">${ comment_data[i].userName }</p>
              <p>${ comment_data[i].content }</p>
            </div>
            <span>
              ${ comment_data[i].commentDate }
              <button class="float-end comment-del" onclick="comment_delete(this)" id="comment-delete-${comment_data[i].commentPk}" data-commentdel-id="${comment_data[i].commentPk}" style="border: 0; background: none;">
                삭제
              </button>
            </span>
          </div>
          <hr>
          `)
        } else {
          comments.insertAdjacentHTML('beforeend',  
          `
          <p>${ comment_data[i].userName }: ${ comment_data[i].content }</p>
          `)
    }
  }
})}
</script>
{% endblock js %} {% endcomment %}

reviews/templates/reviews/index.html
{% comment %} {% extends 'base.html' %}




{% block content %}
{% include 'main-nav.html' %}

  <a class="btn btn-primary" href="{% url 'reviews:create' %}">새글 쓰기</a>
  {% for review in  reviews %}

  <a href="{% url 'reviews:detail' review.pk %}"><p>{{ review.playId.playname }} | {{ review.title }}</p></a>
  <hr>
  {% endfor %}
{% include 'sub-footer.html' %}
{% endblock content %}
{% endcomment %}