accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:user_pk>/", views.profile, name="profile"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("password/", views.pw_change, name="pw_change"),
    path("delete/", views.delete, name="delete"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
    path('blockuser/', views.blockuser, name='blockuser'),
    path('<int:user_pk>/block/', views.block, name='block'),
    path('<int:pk>/block_user_block', views.block_user_block, name='block_user_block'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.main, name="main"),
    path("search/", views.search, name="search"),
    path("articles/", views.index, name="index"),
    path("articles/d/<str:performance_pk>/", views.detail, name="detail"),
    path("articles/<str:performance_pk>/like/", views.like, name="like"),
    path("articles/ranking/", views.ranking, name="ranking"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.
class User(AbstractUser):
    kakao_id = models.BigIntegerField(null=True, unique=True)
    naver_id = models.CharField(null=True, unique=True, max_length=100)
    image = ProcessedImageField(
        upload_to="media/",
        blank=True,
        processors=[ResizeToFill(100, 100)],
        format="JPEG",
        options={"quality": 80},
    )
    followings = models.ManyToManyField(
        "self", symmetrical=False, related_name="followers"
    )
    blockings = models.ManyToManyField('self', symmetrical=False, related_name='blockers')
    def profile_image(self):
        if self.image and hasattr(self.image, "url"):
            return self.image.url
        else:
            return "https://postfiles.pstatic.net/MjAyMDExMDFfMTA1/MDAxNjA0MjI4ODc1Mzk0.05ODadJdsa3Std55y7vd2Vm8kxU1qScjh5-3eVJ9T-4g.h7lHansSdReVq7IggiFAc44t2W_ZPTPoZWihfRMB_TYg.JPEG.gambasg/%EC%9C%A0%ED%8A%9C%EB%B8%8C_%EA%B8%B0%EB%B3%B8%ED%94%84%EB%A1%9C%ED%95%84_%ED%8C%8C%EB%9E%91.jpg?type=w773"

reviews/models.py
from django.db import models
from django.conf import settings
from articles.models import PlayDetail


class Review(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    grades = [
        ("1", "⭐"),
        ("2", "⭐⭐"),
        ("3", "⭐⭐⭐"),
        ("4", "⭐⭐⭐⭐"),
        ("5", "⭐⭐⭐⭐⭐"),
    ]
    grade = models.CharField(max_length=20, choices=grades, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    playId = models.ForeignKey(PlayDetail, on_delete=models.CASCADE)


class ReviewPhoto(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="images/", blank=True)


class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = [
            "username",
            "email",
        ]


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = get_user_model()
        fields = [
            "email",
            "image",
        ]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import requests


def index(request):
    return render(request, "accounts/index.html")


def signup(request):

    if not request.user.is_authenticated:
        if request.method == "POST":
            signup_form = CustomUserCreationForm(request.POST)
            if signup_form.is_valid():
                user = signup_form.save()
                auth_login(request, user)
                return redirect("articles:main")
        else:
            signup_form = CustomUserCreationForm()

        context = {
            "form": signup_form,
        }

        return render(request, "accounts/signup.html", context)
    else:
        # 이미 로그인된 상태입니다 메시지 띄우기
        return redirect("accounts:index")


def login(request):

    if not request.user.is_authenticated:
        login_form = AuthenticationForm(request, data=request.POST)
        if request.method == "POST":
            if login_form.is_valid():
                auth_login(request, login_form.get_user())
                return redirect(request.GET.get("next") or "articles:main")
        else:
            login_form = AuthenticationForm()
        context = {
            "form": login_form,
        }
        return render(request, "accounts/login.html", context)
    else:
        # 이미 로그인된 상태입니다 메시지 띄우기
        return redirect("accounts:index")


def logout(request):
    auth_logout(request)
    return redirect("articles:main")


@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile", request.user.pk)
    else:
        form = CustomUserChangeForm(request.FILES, instance=request.user)
    context = {
        "form": form,
    }
    return render(request, "accounts/update.html", context)


def profile(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    context = {
        "user": user,
        "my": request.user,
        "performance": user.performance.all().order_by("-pk"),
        "followings": user.followings.all(),
        "followers": user.followers.all(),
    }
    return render(request, "accounts/profile.html", context)


@login_required
def pw_change(request):

    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("accounts:profile")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        "form": form,
    }

    return render(request, "accounts/form.html", context)


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)

    return redirect("articles:main")


# Follow
def follow(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    if user != request.user:
        if user.followings.filter(pk=request.user.pk).exists():
            user.followings.remove(request.user)
            is_followed = False
        else:
            user.followings.add(request.user)
            is_followed = True
        return JsonResponse(
            {
                "is_followed": is_followed,
                "followers_count": user.followings.count(),
                "followings_count": user.followers.count(),
            }
        )
    return redirect("accounts:profile", user_pk)


# 소셜로그인
import secrets

state_token = secrets.token_urlsafe(16)


def kakao_request(request):
    kakao_api = "https://kauth.kakao.com/oauth/authorize?response_type=code"
    redirect_uri = "http://goldentiket.shop/accounts/login/kakao/callback"
    client_id = "72b73a1d5e11f6c8e5ebb51f86c0dfab"  # 배포시 보안적용 해야함
    return redirect(f"{kakao_api}&client_id={client_id}&redirect_uri={redirect_uri}")


def kakao_callback(request):
    data = {
        "grant_type": "authorization_code",
        "client_id": "72b73a1d5e11f6c8e5ebb51f86c0dfab",  # 배포시 보안적용 해야함
        "redirect_uri": "http://goldentiket.shop/accounts/login/kakao/callback",
        "code": request.GET.get("code"),
    }
    kakao_token_api = "https://kauth.kakao.com/oauth/token"
    access_token = requests.post(kakao_token_api, data=data).json()["access_token"]

    headers = {"Authorization": f"bearer ${access_token}"}
    kakao_user_api = "https://kapi.kakao.com/v2/user/me"
    kakao_user_information = requests.get(kakao_user_api, headers=headers).json()

    kakao_id = kakao_user_information["id"]
    kakao_nickname = kakao_user_information["properties"]["nickname"]
    kakao_profile_image = kakao_user_information["properties"]["profile_image"]

    if get_user_model().objects.filter(kakao_id=kakao_id).exists():
        kakao_user = get_user_model().objects.get(kakao_id=kakao_id)
    else:
        kakao_login_user = get_user_model()()
        kakao_login_user.username = kakao_nickname
        kakao_login_user.kakao_id = kakao_id
        kakao_login_user.set_password(str(state_token))
        kakao_login_user.save()
        kakao_user = get_user_model().objects.get(kakao_id=kakao_id)
    auth_login(request, kakao_user, backend="django.contrib.auth.backends.ModelBackend")
    return redirect(request.GET.get("next") or "articles:main")


def naver_request(request):
    naver_api = "https://nid.naver.com/oauth2.0/authorize?response_type=code"
    client_id = "mwAzJRdaHS860HumilZ7"  # 배포시 보안적용 해야함
    redirect_uri = "http://goldentiket.shop/accounts/login/naver/callback"
    state_token = secrets.token_urlsafe(16)
    return redirect(
        f"{naver_api}&client_id={client_id}&redirect_uri={redirect_uri}&state={state_token}"
    )


def naver_callback(request):
    data = {
        "grant_type": "authorization_code",
        "client_id": "mwAzJRdaHS860HumilZ7",  # 배포시 보안적용 해야함
        "client_secret": "Aa7AEd9pZ6",
        "code": request.GET.get("code"),
        "state": request.GET.get("state"),
        "redirect_uri": "http://goldentiket.shop/accounts/login/naver/callback",
    }
    naver_token_request_url = "https://nid.naver.com/oauth2.0/token"
    access_token = requests.post(naver_token_request_url, data=data).json()[
        "access_token"
    ]

    headers = {"Authorization": f"bearer {access_token}"}
    naver_call_user_api = "https://openapi.naver.com/v1/nid/me"
    naver_user_information = requests.get(naver_call_user_api, headers=headers).json()

    naver_id = naver_user_information["response"]["id"]
    naver_nickname = naver_user_information["response"]["nickname"]

    if get_user_model().objects.filter(naver_id=naver_id).exists():
        naver_user = get_user_model().objects.get(naver_id=naver_id)
    else:
        naver_login_user = get_user_model()()
        naver_login_user.username = naver_nickname
        naver_login_user.naver_id = naver_id
        naver_login_user.set_password(str(state_token))
        naver_login_user.save()
        naver_user = get_user_model().objects.get(naver_id=naver_id)
    auth_login(request, naver_user, backend="django.contrib.auth.backends.ModelBackend")

    return redirect(request.GET.get("next") or "articles:main")


# 회원차단
@login_required
def block(request, user_pk):
    user = get_object_or_404(get_user_model(), pk=user_pk)
    if user != request.user:
        if user.blockers.filter(pk=request.user.pk).exists():
            user.blockers.remove(request.user)
            user.save()
        else:
            user.blockers.add(request.user)
            user.save()
    return redirect("accounts:profile", user_pk)


@login_required
def blockuser(request):
    block_users = request.user.blockings.all()
    return render(request, "accounts/blockuser.html", {"block_users": block_users})


@login_required
def block_user_block(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    if user != request.user:
        if user.blockers.filter(pk=request.user.pk).exists():
            user.blockers.remove(request.user)
            user.save()
        else:
            user.blockers.add(request.user)
            user.save()
    return redirect("accounts:blockuser")

accounts/templates/accounts/blockuser.html
{% extends 'base.html' %} 
{% load django_bootstrap5 %} 
{% block content %}

<div class="container">

    {% for blockuser in block_users %}
    <div class="card m-4 p-2">
        <div class="d-flex justify-content-center">
            {% if blockuser.profile.image %}
            <img src="{{blockuser.profile.image.url}}" class="" alt="" style="height: 100px; width:100px;"> {% else %}
            <img src="/static/img/bros_blank.png" class="" alt="" style="height: 100px; width:100px;"> {% endif %}

            <p class="align-self-center pt-3 ms-4"><a class="navbar-brand ms-4" href="{% url 'accounts:profile' blockuser.username %} ">{{ blockuser.username }}</a></p>
            <a class="ms-5 align-self-center text-decoration-none text-black fw-bold" href="{% url 'accounts:block_user_block' blockuser.pk %}">차단 취소</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'nav.html' %}

<div class="container mt-5" style="width:50%">
  <h1>accounts/index</h1>
  
  {% if request.user.is_authenticated %}
  <p>로그인 상태: {{ request.user }}</p>
  <p><a href="{% url 'accounts:profile' request.user.pk %}">프로필정보</a></p>
  <p><a href="{% url 'accounts:logout' %}">로그아웃</a></p>
  {% else %}
  <p><a href="{% url 'accounts:signup' %}">가입하기</a></p>
  <p><a href="{% url 'accounts:login' %}">로그인하기</a></p>
  {% endif %}
</div>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block content %}
<section class="login_bg">
  <div class="container d-flex justify-content-center">
    <div class="box_bg boxbgwid p-5">
      <h1 class="text-center mb-5">로그인</h1>
      
      <form action="{% url 'accounts:login' %}" method='POST' onsubmit="return frm_check();">
        {% csrf_token %}
        {% render_field form.username class="form-control w-70" placeholder="아이디를 입력하세요" type="text" name="id" id="logId" %}
        {% render_field form.password class="form-control w-70 my-3" placeholder="비밀번호를 입력하세요" %}
        <!--아이디저장, 찾기 묶음-->
        <div class="box d-flex flex-row justify-content-between mb-3">
        <span class="input-wrap">
          <input type="checkbox" name="saveId" id="saveId">
          <label for="saveId">
            <span></span></label>
          아이디 저장
        </span>
      </div>
        <div class="text-center"><input class="btn account_btn w-100" type="submit" value="로그인"></div>
      </form>
      <p class="text-center my-3">간편 로그인</p>
        <div class="d-flex flex-row" style="justify-content: space-evenly; ">
          <a href="{% url 'accounts:login' %}kakao"><img class="social_btn" src="https://www.ichrogene.kr/assets/img/kakako-icon.png" alt="kakao_login"></a>
          <a href="{% url 'accounts:login' %}naver"><img class="social_btn" src="{% static 'img/naverr.png' %}" alt="naver_login"></a>
        </div>
      <p class="text-center my-5">아직 회원이 아니신가요?<a href="{% url 'accounts:signup' %}"> 👉회원가입</a></p>
    </div>
  </div>
</section>
  {% endblock content %}

  {% block js %}

  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript">
    $(function () {

      fnInit();

    });

    function frm_check() {
      saveid();
    }

    function fnInit() {
      var cookieid = getCookie("saveid");
      console.log(cookieid);
      if (cookieid != "") {
        $("input:checkbox[id='saveId']").prop("checked", true);
        $('#logId').val(cookieid);
      }

    }

    function setCookie(name, value, expiredays) {
      var todayDate = new Date();
      todayDate.setTime(todayDate.getTime() + 0);
      if (todayDate > expiredays) {
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + expiredays + ";";
      } else if (todayDate < expiredays) {
        todayDate.setDate(todayDate.getDate() + expiredays);
        document.cookie = name + "=" + escape(value) + "; path=/; expires=" + todayDate.toGMTString() + ";";
      }

      console.log(document.cookie);
    }

    function getCookie(Name) {
      var search = Name + "=";
      console.log("search : " + search);

      if (document.cookie.length > 0) { // 쿠키가 설정되어 있다면
        offset = document
          .cookie
          .indexOf(search);
        console.log("offset : " + offset);
        if (offset != -1) { // 쿠키가 존재하면
          offset += search.length;
          // set index of beginning of value
          end = document
            .cookie
            .indexOf(";", offset);
          console.log("end : " + end);
          // 쿠키 값의 마지막 위치 인덱스 번호 설정
          if (end == -1) 
            end = document.cookie.length;
          console.log("end위치  : " + end);

          return unescape(document.cookie.substring(offset, end));
        }
      }
      return "";
    }

    function saveid() {
      var expdate = new Date();
      if ($("#saveId").is(":checked")) {
        expdate.setTime(expdate.getTime() + 1000 * 3600 * 24 * 30);
        setCookie("saveid", $("#logId").val(), expdate);
      } else {
        expdate.setTime(expdate.getTime() - 1000 * 3600 * 24 * 30);
        setCookie("saveid", $("#logId").val(), expdate);

      }
    }
  </script>
{% endblock js %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'nav.html' %}

<div class="container">
    <!-- Profile -->
  <div class="profile-detail my-5">
    <!-- Profile-Image -->
    <div class="pd__img w-25 me-5">
      <img src="{{ user.profile_image }}" alt="profile-image">
    </div>
    <!-- Profile-Info -->
    <div class="pd__info w-50 ms-5">
      <!-- Info-Top -->
      <div class="pd__info-top">
        <div class="pd__info__username">
          <h3>{{ user.username }}</h3>
          <p class="mx-3">✅</p>
        </div>
        <!-- Info-Button -->
        <div class="pd__info__btn">
          <!-- Followings -->
          <form id='follow-form' data-user-id='{{ user.pk }}' data-my-id="{{ my.pk }}">
            {% csrf_token %}
            {% if request.user != user %}
              {% if request.user in user.followings.all %}
                <button type='submit' style="
              border: 0;
              background: none;
              border: 1px solid var(--gray-light--color);
              border-radius: 5px;
              padding: 3px 25px;
              margin: 0 10px 0 20px;">
                  <i id="follow-{{ request.user.pk }}" class="fa-solid fa-user-check"></i>
                </button>
              {% else %}
                <button type='submit' style="
              border: 0;
              background: none;
              border: 1px solid var(--gray-light--color);
              border-radius: 5px;
              padding: 3px 25px;
              margin: 0 10px 0 20px;">
                  <i id="follow-{{ request.user.pk }}" class="fa-solid fa-user-plus"></i>
                </button>
              {% endif %}
            {% endif %}
          </form>
          <span class="pd__info__btn-arrow">
            <i class="fa-solid fa-chevron-down"></i>
          </span>

          <!-- Button trigger modal -->
          <button data-bs-toggle="modal" data-bs-target="#exampleModal" style="background: none; border: 0;">
            <i class="fa-solid fa-ellipsis fa-lg"></i>
          </button>

          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-accounts-detail">
              <div class="container">
                <div class="modal-content text-center">
                  <!-- Modal-Body -->
                  <div class="modal-body p-0 accounts-modal">
                    <a href="#" class="fw-bold text-danger">
                      {% if request.user == user %} {% else %}
                      <a href="{% url 'accounts:block' user.pk %}" class="text-decoration-none">
                        {% if request.user in user.blockers.all %}
                        <p class="m-0 text-danger" style="padding: 12px">차단 취소</p>
                        {% else %}
                        <p class="m-0 text-danger" style="padding: 12px">차단</p>
                      </a> {% endif %}
                      {% endif %}
                      </p>
                    </a>
                    {% if request.user == user %}
                      <hr class="m-0">
                      <a href="{% url 'accounts:logout' %}" style="color: var(--dark-color);">
                        <p class="m-0" style="padding: 12px">로그아웃</p>
                      </a>
                      <hr class="m-0">
                      <a href="{% url 'accounts:update' %}" style="color: var(--dark-color);">
                        <p class="m-0" style="padding: 12px">정보수정</p>
                      </a>
                      <hr class="m-0">
                      <a href="{% url 'accounts:delete' %}" style="color: var(--dark-color);">
                        <p class="m-0" style="padding: 12px">회원탈퇴</p>
                      </a>
                    {% endif %}
                    <hr class="m-0">
                    <a href="{% url 'accounts:profile' user.pk %}" style="color: var(--dark-color);">
                      <p class="m-0" style="padding: 12px">취소</p>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Modal-End -->
        </div>
      </div>
      <!-- Info-Bottom -->
      <div class="pd__info-bottom my-3">
        <span class="me-2">찜</span>
        <span class="me-3 fw-bold">{{ user.performance.count }}</span>
        <!-- Button trigger modal -->
        <a data-bs-toggle="modal" href="#follow-user">
          <span class="me-1">팔로우</span>
          <span id="followings-count" class="me-3 fw-bold">{{ user.followers.count }}</span>
        </a>
        <a data-bs-toggle="modal" href="#followings-user">
          <span class="me-1">팔로워</span>
          <span id="followers-count" class="me-3 fw-bold">{{ user.followings.count }}</span>
        </a>
      </div>
      <!-- Followers Modal -->
      <div class="modal fade" id="follow-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">팔로잉 유저</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              
              {% if followers %}
                {% for followUser in followers %}
                <a href="{% url 'accounts:profile' followUser.pk %}">
                  <img src="{{ followUser.profile_image }}" alt="" width="45" height="45" style="border-radius: 50%;">  
                </a>
                {% endfor %}
              {% else %}
                <p style="font-size: 14px; color: var(--gray-color);">팔로잉한 유저가 없습니다...</p>
              {% endif %}
                
            </div>
          </div>
        </div>
      </div>
      <!-- Followings Modal -->
      <div class="modal fade" id="followings-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">팔로워 유저</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              
              {% if followings %}
                {% for followingUser in followings %}
                <a href="{% url 'accounts:profile' followingUser.pk %}">
                  <img src="{{ followingUser.profile_image }}" alt="" width="45" height="45" style="border-radius: 50%;">  
                </a>
                {% endfor %}
              {% else %}
              <p style="font-size: 14px; color: var(--gray-color);">팔로워한 유저가 없습니다...</p>
              {% endif %}
                
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Profile-Likes -->
  <div class="profile-likes">
    <h3 class="my-3">🎬 찜한 공연 </h3>
    <!-- Grid -->
    {% if performance %}
      <div class="like-outbox">
        {% for play in performance %}
          <a href="{% url 'articles:detail' play.playid %}">
            <div class="like-box sa sa-up">
              <div class="like-box__item">
                {% if play.poster %}
                  <img src="{{ play.poster }}" alt="like-performance-image">
                  <div class="img__description">
                    <div class="img__description__count">
                      <span class="me-3">
                        <i class="fa-solid fa-heart"></i>
                        {{ play.like_users.count }}
                      </span>
                      <span>
                        <i class="fa-solid fa-user-pen"></i>
                        {{ play.review_set.count }}
                      </span>
                    </div>
                  </div>
                {% else %}
                  <img class="card-img-top rounded-0" src="https://picsum.photos/300/200" style="width: 100%; height: 100%;" alt="empty-image">
                  <div class="img__description">
                    <div class="img__description__count">
                      <span class="me-3">
                        <i class="fa-solid fa-heart"></i>
                        {{ play.like_users.count }}
                      </span>
                      <span>
                        <i class="fa-solid fa-user-pen"></i>
                        {{ play.review_set.count }}
                      </span>
                    </div>
                  </div>
                {% endif %}
              </div>
            </div>
          </a>
        {% endfor %}
      </div>
    {% else %}
      <p>찜한 연극이 없습니다...</p>
    {% endif %}
    <!-- Grid-End -->
    <div class="my-3"></div>
  </div>
</div>

{% endblock content %}


{% block js %}
<!-- CDN axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
  const form = document.querySelector('#follow-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  form.addEventListener('submit', function(event) {
    event.preventDefault()
    const userId = event.target.dataset.userId
    const myId = event
        .target
        .dataset
        .myId
    // request axios
    axios({
      method: 'post',
      url: `/accounts/${userId}/follow/`,
      headers: {'X-CSRFToken': csrftoken}, // csrf token
    })
      // response views
      .then((response) => {
        const isFollowed = response.data.is_followed
        const followBtn = document.querySelector(`#follow-${myId}`)
        if (isFollowed === true) {
          followBtn
            .classList
            .remove('fa-user-plus');
          followBtn
            .classList
            .add('fa-user-check');
        } else {
          followBtn
            .classList
            .remove('fa-user-check');
          followBtn
            .classList
            .add('fa-user-plus');
        }
        // follow counts
        const followersCountTag = document.querySelector('#followers-count')
        const followingsCountTag = document.querySelector('#followings-count')
        const followersCount = response.data.followers_count
        const followingsCount = response.data.followings_count
        followersCountTag.innerText = followersCount
        followingsCountTag.innerText = followingsCount
      })
      .catch((error) => {
        console.log(error.response)
      })
  })
</script>
{% endblock js %}
  