accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("update/", views.update, name="update"),
    path("<int:user_pk>/", views.profile, name="profile"),
    path("<int:user_pk>/follow/", views.follow, name="follow"),
    path("password/", views.pw_change, name="pw_change"),
    path("delete/", views.delete, name="delete"),
    path("login/kakao/", views.kakao_request, name="kakao"),
    path("login/kakao/callback/", views.kakao_callback),
    path("login/naver/", views.naver_request, name="naver"),
    path("login/naver/callback/", views.naver_callback),
    path('blockuser/', views.blockuser, name='blockuser'),
    path('<int:user_pk>/block/', views.block, name='block'),
    path('<int:pk>/block_user_block', views.block_user_block, name='block_user_block'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.main, name="main"),
    path("search/", views.search, name="search"),
    path("articles/", views.index, name="index"),
    path("articles/d/<str:performance_pk>/", views.detail, name="detail"),
    path("articles/<str:performance_pk>/like/", views.like, name="like"),
    path("articles/ranking/", views.ranking, name="ranking"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
    path("reviews/", include("reviews.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GoldenTicket</title>
  
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <!-- Fontawesome -->
  <script src="https://kit.fontawesome.com/3ef4088aa9.js" crossorigin="anonymous" defer></script>
  {% comment %} <script src="{% static 'js/main.js' %}" defer></script> {% endcomment %}
  <!-- CSS base -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
  <!-- Modal-Position -->
  <style>
    .modal-dialog {
      margin-top: 0;
      margin-bottom: 0;
      height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
    }
  </style>
</head>
<body>

  <!-- Block-Content -->
  {% block content %}
  {% endblock  %}


  <!-- Footer -->
  <footer>
    <hr class="gray">
    <div class="container p-3" >

      <div class="footer-txt d-flex justify-content-around">
        <a href='{% url 'articles:main' %}' class="d-flex align-items-center" >
          <img src="{% static 'img/logoblack.png' %}" alt="logo" width="210" height="120">
        </a>
          <div class="footxt d-flex flex-column justify-content-center">
            <p>GoldenTicket</p>
              <p class="github">
                <a href="https://github.com/YoonDii/GoldenTicket" target="_blank">프로젝트 팀 깃허브</a>
                <div class="github d-flex">
                <a href="https://github.com/Jobyeongjin">조병진 |</a>  
                <a href="https://github.com/devhump">&nbsp조수람 |</a>
                <a href="https://github.com/Bonbon315">&nbsp조본희 |</a> 
                <a href="https://github.com/YoonDii">&nbsp김윤지 |</a>  
                <a href="https://github.com/rhoeunbin">&nbsp노은빈</a>
                </div>
              </p>
            <p style="font-size: 14px;">Copyright © GoldenTicket Corp. All Rights Reserved.</p>
          </div>
          <div class=" d-flex flex-column justify-content-center">
            <h1 class="sf-number" style="color: var(--main-color);">2022-1122</h1>
            <table class="sf-walking"> 
              <tr>
                <th>기 간</th>
                <td>11:09 ~ 11:21</td>
                <td class="gray">(공휴일 휴무)</td> 
              </tr>
              <tr>
                <th>발 표</th>
                <td>11:22 ~ 11:00</td>
              </tr>
            </table>
          </div>
      </div>
    </div>
  </footer>

    <a href="#" class="return-top top">
      <img src="{% static 'img/arrowup.png' %}" alt=up> 
    </a>
  </a>




  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<!-- Block-JS -->
{% block js %}
{% endblock js %}
  
</body>
</html>

templates/main-nav.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GoldenTicket</title>
</head>
<body>
  <!-- Main-Nav -->
  <nav class="main-nav">
    <div class="container">
      <div class="main-nav__wrap">
        <div class="m-nav__logo">
          <div class="logo-wrap d-flex align-items-center">
            <input type="checkbox" id="menuicon">
            <label for="menuicon">
              <span></span>
              <span></span>
              <span></span>
            </label>
            <!-- Side Bar -->
            <div class="sidebar">
              <div class="ham_" style="color: #fff"></div>
              <div class="sidebar-menu">
                <ul class="pf-gnb-my-5 mx-4" style="text-align: center;">
                  <li class="dropdown w-100">
                    <a href="{% url 'articles:index' %}?genre=연극" class="w-100">
                      <span class="dd-title dd-title-01" style="color: #fff;">장르</span>
                    </a>
                    <ul class="hide-box">
                      <li><a href="{% url 'articles:index' %}?genre=연극" style="color: #fff"><p>- 연극</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=클래식" style="color: #fff"><p>- 클래식</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=무용" style="color: #fff"><p>- 무용</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=뮤지컬" style="color: #fff"><p>- 뮤지컬</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=국악" style="color: #fff"><p>- 국악</p></a></li>
                    </ul>
                  </li>
                  <li class="dropdown w-100">
                    <a href="{% url 'articles:ranking' %}" class="w-100">
                    <span class="dd-title" style="color: #fff;">오늘의 랭킹</span>
                    </a>
                  </li>
                  <li class="dropdown w-100">

                    {% if request.user.pk %}
                    <a href="{% url 'accounts:profile' request.user.pk %}" class="w-100">
                    <span class="dd-title" style="color: #fff;">마이프로필</span>
                    {% endif %}
                    
                    </a>
                  </li>
                </ul>
              </div>
              <h1 style="text-align: center;">
                <a href="{% url 'articles:main' %}">
                  <img src="{% static 'img/logogray.png' %}" alt="logo" width="160" height="90">
                </a>
              </h1>
            </div>
            <!-- Side Bar-End -->
            <h1>
              <a href="{% url 'articles:main' %}">
                <img src="{% static 'img/logogray.png' %}" alt="logo" width="160" height="90">
              </a>
            </h1>
          </div>
          <ul class="m-nav__nav">
            <li class="m-nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=연극"><p style="color:#fff">연극</p></a></li>
            <li class="m-nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=클래식"><p style="color:#fff">클래식</p></a></li>
            <li class="m-nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=무용"><p style="color:#fff">무용</p></a></li>
            <li class="m-nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=뮤지컬"><p style="color:#fff">뮤지컬</p></a></li>
            <li class="m-nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=국악"><p style="color:#fff">국악</p></a></li>
          </ul>
          <div class="m-nav__search">
            <form id="search-form" action="{% url 'articles:search' %}" role='search'>
              <input type="text" id="search-type" name='search' style="color: var(--white-color);">
              <a href="{% url 'articles:search' %}" role='search' onclick="#">
                <i class="fa-solid fa-magnifying-glass fa-xl"></i>
              </a>
            </form>
            <!-- User Profile -->
            <div class="ms-3">
              {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:profile' request.user.pk %}">
                  <img src="{{ request.user.profile_image }}" alt="profile_image" width="45" height="45" style="border-radius: 50%;">
                </a>
                {% else %}
                <a href="{% url 'accounts:login' %}">
                  <i class="fa-regular fa-user fa-xl"></i>
                </a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <!-- Main-Nav__Wrap-End -->
    </div>
  </nav>

 
  <!-- Visual -->
  <div class="slideshow-container">
    <div class="myslides ">
      <a href="#">
        <img src=" http://tkfile.yes24.com/Upload2/Display/202211/20221104/wel_mv_43948.jpg/dims/quality/70/" alt=""></a>
    </div>
    <div class="myslides ">
      <a href="http://kdtgoldenticketbean-env.eba-nsybrye9.ap-northeast-2.elasticbeanstalk.com/articles/d/PF202152/">
        <img src="http://tkfile.yes24.com/Upload2/Display/202211/20221114/wel_mv_44090.jpg/dims/quality/70/" alt="">
      </a>
    </div>
    <div class="myslides ">
      <a href="http://kdtgoldenticketbean-env.eba-nsybrye9.ap-northeast-2.elasticbeanstalk.com/articles/d/PF201908/">
      <img src="http://tkfile.yes24.com/Upload2/Display/202211/20221110/wel_mv_44048.jpg/dims/quality/70/" alt="">
      </a>
    </div>
    <div class="myslides ">
      <a href="#">
        <img src="http://tkfile.yes24.com/Upload2/Display/202210/20221027/wel_mv_43907.jpg/dims/quality/70/" alt=""></a>
    </div>
    <div class="myslides ">
      <a href="http://kdtgoldenticketbean-env.eba-nsybrye9.ap-northeast-2.elasticbeanstalk.com/search/?search=%EC%BA%A3%EC%B8%A0">
        <img src="http://tkfile.yes24.com/Upload2/Display/202211/20221103/wel_mv_43937_1.jpg/dims/quality/70/" alt=""></a>
    </div>
    <div class="myslides ">
      <a href="#">
        <img src="http://tkfile.yes24.com/Upload2/Display/202211/20221116/wel_mv_btv.jpg/dims/quality/70/" alt=""></a>
    </div>
    <div class="myslides ">
      <a href="#">
        <img src="http://tkfile.yes24.com/Upload2/Display/202207/20220720/wel_mv_.png/dims/quality/70" alt=""></a>
    </div>
    <div class="myslides ">
      <a href="http://kdtgoldenticketbean-env.eba-nsybrye9.ap-northeast-2.elasticbeanstalk.com/articles/d/PF200234/">
        <img src="http://tkfile.yes24.com/Upload2/Display/202210/20221017/wel_mv_2022.jpg/dims/quality/70/" alt=""></a>
    </div>
  </div>

  <div class="prev" onclick="plusS(-1)">&#10094;</div>
  <div class="next" onclick="plusS(1)">&#10095;</div>
  <br>

  <div style="text-align:center">
    <span class="dot" onclick="currentS(1)"></span>
    <span class="dot" onclick="currentS(2)"></span>
    <span class="dot" onclick="currentS(3)"></span>
    <span class="dot" onclick="currentS(4)"></span>
    <span class="dot" onclick="currentS(5)"></span>
    <span class="dot" onclick="currentS(6)"></span>
    <span class="dot" onclick="currentS(7)"></span>
  </div>

  
{% block js %}
<script>
// Carousel
var slideIndex = 1;
showSlides(slideIndex);

function plusS(n) {
  showSlides(slideIndex += n);
}

function currentS(n) {
  showSlides(slideIndex=n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("myslides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i=0;i<dots.length;i++){
    dots[i].className=dots[i].className.replace("active");
  }
  slides[slideIndex - 1].style.display = "block";
  dots[slideIndex - 1].className += "active";
}

//auto
var  slideIndex = 0;
showSlides();

function showSlides() {
  var i ;
  var slides= document.getElementsByClassName("myslides");
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = 'none';
  }
  slideIndex++;
  if (slideIndex > slides.length) {
    slideIndex = 1
  }
  slides[slideIndex -1].style.display = "block";
  setTimeout(showSlides, 3500);
}
</script>
{% endblock js %}
  
</body>
</html>

templates/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GoldenTicket</title>
</head>
<body>
  <!-- Nav -->
  <nav class="sub-nav">
    <div class="container">
      <div class="main-nav__wrap">
        <div class="m-nav__logo">
          <div class="logo-wrap d-flex align-items-center">
            <input type="checkbox" id="menuicon_nav">
              <label for="menuicon_nav">
                <span></span>
                <span></span>
                <span></span>
              </label> 
            <!-- Side Bar -->
            <div class="sidebar">
              <div class="ham_" style="color: #fff"></div>
              <div class="sidebar-menu">
                <ul class="pf-gnb-my-5 mx-4" style="text-align: center;">
                  <li class="dropdown w-100">
                    <a href="{% url 'articles:index' %}?genre=연극" class="w-100">
                      <span class="dd-title dd-title-01" style="color: #fff;">장르</span>
                    </a>
                    <ul class="hide-box">
                      <li><a href="{% url 'articles:index' %}?genre=연극" style="color: #fff"><p>- 연극</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=클래식" style="color: #fff"><p>- 클래식</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=무용" style="color: #fff"><p>- 무용</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=뮤지컬" style="color: #fff"><p>- 뮤지컬</p></a></li>
                      <li><a href="{% url 'articles:index' %}?genre=국악" style="color: #fff"><p>- 국악</p></a></li>
                    </ul>
                  </li>
                  <li class="dropdown w-100">
                    <a href="{% url 'articles:ranking' %}" class="w-100">
                    <span class="dd-title" style="color: #fff;">오늘의 랭킹</span>
                    </a>
                  </li>
                  <li class="dropdown w-100">
                    {% if request.user.pk %}
                    <a href="{% url 'accounts:profile' request.user.pk %}" class="w-100">
                    <span class="dd-title" style="color: #fff;">마이프로필</span>
                    {% endif %}
                    </a>
                  </li>
                </ul>
              </div>
              <h1 style="text-align: center;">
                <a href="{% url 'articles:main' %}">
                  <img src="{% static 'img/logogray.png' %}" alt="logo" width="160" height="90">
                </a>
              </h1>
            </div>
            <!-- Side Bar-End -->
          <h1>
            <a href="{% url 'articles:main' %}">
              <img src="{% static 'img/logoblack.png' %}" alt="logo" width="160" height="90">
            </a>
          </h1>
          </div>
        <ul class="m-nav__nav">
          <li class="nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=연극">연극</a></li>
          <li class="nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=클래식">클래식</a></li>
          <li class="nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=무용">무용</a></li>
          <li class="nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=뮤지컬">뮤지컬</a></li>
          <li class="nav__nav__item hover-underline-animation"><a href="{% url 'articles:index' %}?genre=국악">국악</a></li>
        </ul>
        <div class="nav__search">
          <form action="{% url 'articles:search' %}" role='search' id='searchfunc3'>
            <input type="text" id="search-type-03" name='search'>
            <button type="submit" onclick="">
              <i class="fa-solid fa-magnifying-glass fa-lg m-0"></i>
            </button>
          </form>
          <!-- Search length -->
          <script>
            const btn3 = document.getElementById("searchfunc3")
            btn3.addEventListener("submit", function(event) {
              val = document.getElementById("search-type-03").value.length
              console.log(val)
              if(val <= 1) {
                event.preventDefault()
                alert("검색어는 2글자 이상 입력해주세요")
              }
            })
          </script>
          <!-- User Profile -->
          <div class="ms-3">
            {% if request.user.is_authenticated %}
              <a href="{% url 'accounts:profile' request.user.pk %}">
                <img src="{{ request.user.profile_image }}" alt="profile_image" width="45" height="45" style="border-radius: 50%;">
              </a>
              {% else %}
              <a href="{% url 'accounts:login' %}">
                <i class="fa-regular fa-user fa-xl"></i>
              </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

</body>
</html>

{% block js %}
{% endblock js %} 